name: Lint Codebase

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pylint

    - name: Lint codebase
      run: |
        pylint --fail-under=9
